spring:
  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        # health,info,beans,env,metrics
        include: "*"
  endpoint:
    health:
      show-details: always # default: never

logging:
  level:
    com.sesh.chat.auth: "info"