server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-server:5432/chatapp_user_service
    username: admin
    password: yehorfury!
    driver-class-name: org.postgresql.Driver
  config:
    import: http://config-service:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka