server:
  port: 8001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatapp_user_service
    username: admin
    password: yehorfury!
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka